customerBundle\Entity\EmailLog:
    type: entity
    table: email_log
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        to:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        cc:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        status:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: user_id
    lifecycleCallbacks: {  }
