customerBundle\Entity\Reviews:
    type: entity
    table: reviews
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: user_id
        review:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        productId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: product_id
        rating:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        date:
            type: datetime
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
