customerBundle\Entity\ServiceMasterProductColorSize:
    type: entity
    table: service_master_product_color_size
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        productid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        categoryId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: category_id
        productName:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: product_name
        productColor:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: product_color
        productSize:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: product_size
    lifecycleCallbacks: {  }
