customerBundle\Entity\ServiceMasterProduct:
    type: entity
    table: service_master_product
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        productname:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        isactive:
            type: boolean
            nullable: false
            comment: ''
        date:
            type: date
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
